services:
  cotiledon-dev:
    image: node:22-alpine3.19
    working_dir: /usr/src/app
    environment:
      - AMBIENTE=dev
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    command: 'yarn start:dev'
