## compose de prueba

services:
  cotiledon-prod:
    build:
      context: .
      dockerfile: 'dockerfile'
    environment:
      - AMBIENTE=production
    ports:
      - '8080:8080'
## docker compose --build para generar, en el contenedor, nueva imagen a partir del dockerfile
