version: '3.8'

services:
  database-prod:
    image: mysql:8.0
    container_name: database-prod
    volumes:
      - ~/db/data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=clave123
      - MYSQL_DATABASE=plantai_db
      - MYSQL_HOST=database-prod
    ports:
      - '3306:3306' # Exponiendo el puerto 3306 al host

  cotiledon-prod:
    image: nicolasf1/cotiledonapp:1.0.1
    depends_on:
      - database-prod
    environment:
      - AMBIENTE=production
      - DB_HOST=database-prod
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=clave123
      - DB_DATABASE=plantai_db
    ports:
      - '8080:8080'
