services:
  cotiledon-prod:
    image: nicolasf1/cotiledonapp:1.0.0
    environment:
      - AMBIENTE=production
    ports:
      - '8080:8080'
  database-prod:
    image: mysql:9-oracle
    volumes:
      - ./db/data_prod:/usr/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=clave123
    ports:
      - '3306:3306'
